---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dra-example-driver.fullname" . }}-role
  namespace: {{ include "dra-example-driver.namespace" . }}
rules:
- apiGroups:
  - ""
  - resource.k8s.io
  - gpu.resource.example.com
  - nas.gpu.resource.example.com
  resources: ["*"]
  verbs: ["*"]
